Walle 20241024 1 (#52)
* (fix): 更正 api 介面路徑

* (refactor): format code

* (feat): add material and icons-material package

* (feat): 新增 donateHome 頁面

* (feat): add detailModal component

* (fix): layout w-full property

* (fix): error TS6133: 'event' is declared but its value is never read.